"use client";

import { useMemo, useState } from "react";
import { Copy, Eye, Loader2, MoreHorizontal, Search, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DataEmpty, DataError, DataLoading } from "@/components/ui/data-state";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ScriptSectionCard } from "@/components/dashboard/script-section-card";
import { TeamPageShell } from "@/components/dashboard/team/team-page-shell";
import { useTeamScripts } from "@/hooks/use-team-scripts";
import { deleteTeamScript, fetchTeamScriptById, formatTeamErrorDetails } from "@/lib/api/team-client";
import { formatDate } from "@/lib/team/format";
import { canManageScripts } from "@/lib/team/permissions";
import type { ScriptHistoryItem } from "@/lib/auth/script-history";
import { buildFullScriptText } from "@/lib/scripts/export";

export function TeamScriptsView() {
  const {
    scripts,
    role,
    scriptCount,
    loading,
    initializing,
    error,
    errorDetails,
    refresh,
  } = useTeamScripts();
  const [query, setQuery] = useState("");
  const [preview, setPreview] = useState<{
    script: ScriptHistoryItem;
    authorName: string;
  } | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [actionId, setActionId] = useState<string | null>(null);

  const filtered = useMemo(() => {
    if (!query.trim()) return scripts;
    const q = query.toLowerCase();
    return scripts.filter(
      (script) =>
        script.title.toLowerCase().includes(q) ||
        script.authorName.toLowerCase().includes(q) ||
        (script.videoType?.toLowerCase().includes(q) ?? false)
    );
  }, [query, scripts]);

  async function openPreview(scriptId: string) {
    setPreviewLoading(true);
    try {
      const data = await fetchTeamScriptById(scriptId);
      setPreview(data);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to load script");
    } finally {
      setPreviewLoading(false);
    }
  }

  async function handleCopyHook(hook: string, title: string) {
    await navigator.clipboard.writeText(hook);
    toast.success(`Hook copied from "${title}"`);
  }

  async function handleCopyFull(script: ScriptHistoryItem) {
    await navigator.clipboard.writeText(buildFullScriptText(script));
    toast.success("Full script copied to clipboard");
  }

  async function handleDelete(scriptId: string, title: string) {
    if (!window.confirm(`Delete team script "${title}"?`)) return;

    setActionId(scriptId);
    try {
      await deleteTeamScript(scriptId);
      toast.success("Script deleted");
      setPreview(null);
      await refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to delete script");
    } finally {
      setActionId(null);
    }
  }

  const canManage = role ? canManageScripts(role) : false;
  const pageDescription = "All scripts generated by your workspace members";

  if (loading || initializing) {
    return (
      <TeamPageShell title="Team Scripts" description={pageDescription}>
        <DataLoading
          message={initializing ? "Creating your workspace..." : "Loading team scripts..."}
        />
      </TeamPageShell>
    );
  }

  if (error) {
    return (
      <TeamPageShell title="Team Scripts" description={pageDescription}>
        <DataError message={error} details={formatTeamErrorDetails(errorDetails)} />
      </TeamPageShell>
    );
  }

  return (
    <TeamPageShell title="Team Scripts" description={pageDescription}>
      <div className="space-y-4">
        <div className="saas-card rounded-xl p-4 sm:p-5">
          <div className="relative max-w-md">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search by title, author, or type..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="border-border bg-white pl-9"
            />
          </div>
          <p className="mt-3 text-xs text-muted-foreground">
            {filtered.length} of {scriptCount} team scripts
          </p>
        </div>

        {scripts.length === 0 ? (
          <DataEmpty
            title="No team scripts yet"
            description="Scripts generated by workspace members will appear here."
          />
        ) : (
          <div className="saas-card overflow-hidden rounded-xl">
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead>Script Title</TableHead>
                    <TableHead className="hidden sm:table-cell">Author</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead className="hidden md:table-cell">Created</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filtered.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={5} className="h-24 text-center text-muted-foreground">
                        No scripts match your search.
                      </TableCell>
                    </TableRow>
                  ) : (
                    filtered.map((script) => (
                      <TableRow key={script.id}>
                        <TableCell>
                          <p className="font-medium">{script.title}</p>
                          <p className="mt-0.5 line-clamp-1 text-xs text-muted-foreground sm:hidden">
                            {script.authorName}
                          </p>
                        </TableCell>
                        <TableCell className="hidden text-muted-foreground sm:table-cell">
                          {script.authorName}
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Badge variant="muted" className="font-normal">
                              {script.videoType ?? "—"}
                            </Badge>
                            {script.shared && (
                              <Badge variant="muted" className="text-[10px] font-normal">
                                Shared
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell className="hidden text-muted-foreground md:table-cell">
                          {formatDate(script.createdAt)}
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="flex items-center justify-end gap-1">
                            <Button
                              variant="ghost"
                              size="sm"
                              className="hidden h-8 gap-1.5 text-xs sm:inline-flex"
                              onClick={() => void openPreview(script.id)}
                              disabled={previewLoading}
                            >
                              <Eye className="h-3.5 w-3.5" />
                              View
                            </Button>
                            <DropdownMenu>
                              <DropdownMenuTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-8 w-8"
                                  aria-label={`Actions for ${script.title}`}
                                >
                                  <MoreHorizontal className="h-4 w-4" />
                                </Button>
                              </DropdownMenuTrigger>
                              <DropdownMenuContent align="end">
                                <DropdownMenuItem
                                  onClick={() => void openPreview(script.id)}
                                >
                                  <Eye className="mr-2 h-4 w-4" />
                                  View script
                                </DropdownMenuItem>
                                <DropdownMenuItem
                                  onClick={() =>
                                    handleCopyHook(script.hook, script.title)
                                  }
                                >
                                  <Copy className="mr-2 h-4 w-4" />
                                  Copy hook
                                </DropdownMenuItem>
                                {canManage && (
                                  <DropdownMenuItem
                                    className="text-red-600 focus:text-red-600"
                                    onClick={() =>
                                      void handleDelete(script.id, script.title)
                                    }
                                    disabled={actionId === script.id}
                                  >
                                    <Trash2 className="mr-2 h-4 w-4" />
                                    Delete
                                  </DropdownMenuItem>
                                )}
                              </DropdownMenuContent>
                            </DropdownMenu>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </div>
        )}
      </div>

      {(preview || previewLoading) && (
        <div className="fixed inset-0 z-50 flex items-end justify-center bg-gray-900/20 p-4 sm:items-center">
          <div
            className="saas-card max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl p-6 shadow-2xl"
            role="dialog"
            aria-modal="true"
          >
            {previewLoading && !preview ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            ) : preview ? (
              <>
                <div className="mb-4 flex items-start justify-between gap-4">
                  <div>
                    <h2 className="text-lg font-semibold">{preview.script.topic}</h2>
                    <p className="mt-1 text-xs text-muted-foreground">
                      by {preview.authorName} · {formatDate(preview.script.createdAt)}
                    </p>
                  </div>
                  <button
                    type="button"
                    onClick={() => setPreview(null)}
                    className="rounded-md p-2 text-muted-foreground hover:bg-gray-50 hover:text-foreground"
                    aria-label="Close preview"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
                <div className="grid gap-3">
                  <ScriptSectionCard title="Hook" content={preview.script.output.hook} />
                  <ScriptSectionCard title="Intro" content={preview.script.output.intro} />
                  <ScriptSectionCard
                    title="Main Script"
                    content={preview.script.output.mainScript}
                  />
                  <ScriptSectionCard title="CTA" content={preview.script.output.cta} />
                </div>
                <div className="mt-4 flex gap-2">
                  <Button
                    variant="outline"
                    className="flex-1"
                    onClick={() =>
                      handleCopyHook(preview.script.output.hook, preview.script.topic)
                    }
                  >
                    <Copy className="h-4 w-4" />
                    Copy Hook
                  </Button>
                  <Button
                    variant="violet-glow"
                    className="flex-1"
                    onClick={() => void handleCopyFull(preview.script)}
                  >
                    <Copy className="h-4 w-4" />
                    Copy Full Script
                  </Button>
                </div>
              </>
            ) : null}
          </div>
        </div>
      )}
    </TeamPageShell>
  );
}
